### ISSUE TITLE
'TaboolaSDK/TaboolaSDK.h' file not found

### ISSUE THREAD

**Issue by rochapablo** [taboola/taboola-react-native-example#11]
I have clone the repository, then I run `npm i`, `cd ios`, `pod install`.

What could I be missing here?

**Comment by omriariav** [comment]
@rochapablo we're not monitoring the github repo for issues; you can use our support forum - https://developers.taboola.com/taboolasdk/discuss 

please make you specifically mention iOS SDK 2.8.2 in the pod file (see here: https://developers.taboola.com/taboolasdk/docs/taboola-react-native-plugin#ios)
